### ISSUE TITLE
Exercise 1

### ISSUE THREAD

**Issue by brentonmcs** [simonech/ray-tracer-challenge-netcore#2]
Hey,

With your Projectile's velocity, I believe it should be normalised "Tuple.Vector(1, 1, 0).Normalise()"

P.S Thanks for kicking off this - I've got the book and I'm following along!

**Comment by simonech** [comment]
You are indeed correct! Thx for spotting it!
I'll be posting my progress on my blog too (http://codeclimber.net.nz) if you also want to read a more prosaic version of the code (or also just read them here in the blog-posts folder)
